# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:11.0

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            # build holoflows-kit
            - run: |
                  cd ..
                  git clone -q --depth=1 https://github.com/DimensionFoundation/holoflows-kit
            - restore_cache:
                  keys:
                      - v1-dependencies-holoflows-{{ checksum "~/holoflows-kit/package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-holoflows-
            - run: |
                  cd ../holoflows-kit
                  yarn install
            - save_cache:
                  paths:
                      - ~/holoflows-kit/node_modules
                  key: v1-dependencies-holoflows-{{ checksum "~/holoflows-kit/package.json" }}
            - run: |
                  cd ../holoflows-kit
                  yarn build
                  yarn link

            # build maskbook
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn link @holoflows/kit
            - run: yarn build
            - run: sudo apt-get install zip
            - run: zip -r build.zip build/
            - store_artifacts:
                  path: build.zip
